### PR TITLE
Fix the issue: one tag with comma separate values are not corrected p…

### PR DESCRIPTION
**Pull request by zyzjaffery**
…arsed in []string

https://github.com/lsegal/gucumber/issues/9

### CODE REVIEW

**Comment by zyzjaffery** [comment]
I attempted to write unit test for the modified Set method, however the init() in run_main will be run twice by the unit test execution, and flag is not happy about register the same argument twice.

**Comment by lsegal** [comment]
Sorry this is super late (I hadn't seen this patch), but it looks like this would stop Set() from appending tags across multiple calls?

**Comment by zyzjaffery** [comment]
Maybe this is my misunderstanding of "comma-separated list of tags to filter scenarios by". I thought passing multiple tags by "-tags=@tag1,@tag2,@tag3". Looks like it should be "-tags=@tag1, -tags=@tag2"

**Comment by lsegal** [comment]
Using `-tags=@tag1 -tags=@tag2` should be supported (and equivalent to `-tags=@tag1,@tag2`).

**Comment by lsegal** [comment]
Closing this because we would have to support multiple tag options.

**Pull request closed without merging**
